name: flutter_getx_template
description: Boilarplate template of Flutter GetX.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: '2.8.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  flutter_svg: ^2.0.7
  dio: ^5.2.1
  shared_preferences: ^2.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  logger: ^1.4.0
  pretty_dio_logger: ^1.3.1
  font_awesome_flutter: ^10.5.0
  flutter_easyloading: ^3.0.5
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: any
  dart_code_metrics: any
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "images/launcher_icon.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 200
        - asset: fonts/Roboto-Light.ttf
          weight: 200
        - asset: fonts/Roboto-Regular.ttf
          weight: 200
        - asset: fonts/Roboto-Medium.ttf
          weight: 300
        - asset: fonts/Roboto-Bold.ttf
          weight: 600
        - asset: fonts/Roboto-Italic.ttf
          style: italic
